version: '3'

services:
  booking:
    build: booking-module/
    depends_on:
      - 'database'
    ports: 
      - '3004:3004'
    command: >
      sh -c "npm run seed && npm run build && npm start"

  database:
    image: mongo:latest
